version: '3'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
  web:
    build: .
    command: python /app/recruitment_task/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/media
    ports:
      - "8000:8000"
    depends_on:
      - db