version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  web:
    build: .
    command: python /app/recruitment_task/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/media
    ports:
      - "8000:8000"
    depends_on:
      - db