# Generated by Django 4.2.5 on 2023-09-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_email_alter_users_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user_id',
            new_name='user',
        ),
    ]
