# Generated by Django 4.2.5 on 2023-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_id_images_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
