# Generated by Django 4.2.5 on 2023-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_images_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
