# Generated by Django 4.2.5 on 2023-09-21 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_imagesadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_id', models.CharField(max_length=100)),
                ('expiration_time', models.IntegerField(max_length=100)),
            ],
        ),
    ]
