# Generated by Django 4.2.5 on 2023-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_linksadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksadmin',
            name='expiration_time',
            field=models.IntegerField(),
        ),
    ]
