# Generated by Django 4.2.5 on 2023-09-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_images_user_id_alter_images_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_path',
            new_name='path',
        ),
    ]
