# Generated by Django 4.2.5 on 2023-09-21 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_image_format_images_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.ImageField(unique=True, upload_to='')),
                ('format', models.CharField(max_length=100)),
            ],
        ),
    ]
